export const REACT_APP_SUPABASE_URL =
  "https://zpfetnpspgkopskfuoom.supabase.co";
export const REACT_APP_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZmV0bnBzcGdrb3Bza2Z1b29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjgyNDYyNzEsImV4cCI6MTk4MzgyMjI3MX0.ZtDKiFhhuK7iSA_ukmQgx7olgi9BrCxZ79_Cb9l3wYE";
